package org.me.gcu.equakestartercode;

public enum SortMode {
    MAGNITUDE_ASCENDING, MAGNITUDE_DESCENDING, DATE_ASCENDING, DATE_DESCENDING, ALPHABETICAL_ASCENDING, ALPHABETICAL_DESCENDING, DEPTH_ASCENDING, DEPTH_DESCENDING
}
